//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public System.Guid Id { get; set; }
        public string IssueTitle { get; set; }
        public string IssueDesc { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Status { get; set; }
        public string RaisedBy { get; set; }
        public Nullable<System.DateTime> RaisedOn { get; set; }
        public Nullable<System.DateTime> TargetResolutionDate { get; set; }
        public Nullable<System.DateTime> ActualResolutionDate { get; set; }
        public Nullable<System.DateTime> ResolutionSummary { get; set; }
        public string ResolvedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.Guid ProjectID { get; set; }
    }
}
