//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueTracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDetail
    {
        public System.Guid Id { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDesc { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
